task:
  name: ci/build

  container:
    image: debian:11
    kvm: true

  env:
    PACKER_URL: https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_amd64.zip
    PATH: ${PATH}:/usr/local/bin

  prepare_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        libguestfs-tools
        make
        qemu-system-x86
        unzip
    - wget "$PACKER_URL" -O /tmp/packer.zip --no-verbose
    - cd /usr/local/bin && unzip /tmp/packer.zip
    - ls -lh /usr/local/bin
    - packer --version

  build_script:
    - make build VERSION=13.2-STABLE

  always:
    console_log_script:
      - cat console.log || true
